### ISSUE TITLE
web interface calls to generate data in other formats

### ISSUE THREAD

**Issue by maojunxyz** [easysoft/zendata#18]
[web接口调用](https://www.zendata.cn/book/zendata/why-zendata-115.html)

Is it possible to support data generation by configuring the format in yaml and then generate it directly through web interface calls?

It is possible to output data in other formats at the command line, but I have to maintain my command line scripts. Why not integrate it into a web page to manage it?

**Comment by maojunxyz** [comment]
By generating data in other formats through web calls, I can then integrate it into other web services or tools.

**Comment by aaronchen2k** [comment]
yes, you can call zendata web api to generate test data in json format.

**Comment by maojunxyz** [comment]
> yes, you can call zendata web api to generate test data in json format.

The command line supports a total of 7 data types, but the web has only json type. 

Please support returning other types of data.

**Comment by aaronchen2k** [comment]
使用JSON格式输出，是因为它很容易被转换成各种语言的对象，作为测试数据用于脚本中。不是很明白为什么需要其他格式的接口输出。
