### ISSUE TITLE
sql 转换成yaml 问题（待回复）

### ISSUE THREAD

**Issue by senmen111** [easysoft/zendata#20]
Create sql 里面如果有索引。 则转换出来的 yaml 模板 ，会将index 作为 字段 生成到 yaml 里面
 如果创建的table a  sql 命令'a' 和（） 中间有多个空格，那么创建的yaml 文件为  a  .yaml ，正常应该是 a.yaml

**Comment by aaronchen2k** [comment]
多个空格造成表名错误的问题，已修复；
索引的问题，KEY     `fk_project_id_idx` (`project_id`)这种情况下是好的 ，请提供详细信息。
