### ISSUE TITLE
支持图关系数据生成？

### ISSUE THREAD

**Issue by melin** [easysoft/zendata#3]
测试图产品时，需要关系数据，是否支持关系数据生成？

**Comment by easysoft** [comment]
可否具体讲讲业务场景？最好给个例子。

**Comment by dropping** [comment]
图数据需求：定义点（多个类型，属性），边（点>点，多个类型），可设定网络大小，比如1万个点，10万条边，最大的联通图100个点，大部分点的度数接近平均度数。

**Comment by easysoft** [comment]
可否给点具体的数据格式？我们来试试。

**Comment by dropping** [comment]
比如：
点）企业：ID，名称
点）人：ID，姓名
边）企业>企业：投资，金额，时间
边）人>企业：投资，金额，时间
边）人>人：转账，金额，时间

造数据构建一个关系网络，满足：
节点数 10000
关系数 100000
单群体最大节点数 100

**Comment by easysoft** [comment]
我理解的应该是有五种数据：

1. 企业数据。
2. 人的数据。
3. 企业和企业的交易。
4. 人和企业的交易。
5. 人和人的交易。
用zd来生成的话，可以定义五种数据。还是很好定义的。

企业：
fields:
  - field: id
  - range: 1-100000
  - field: name
  - prefix: 公司
  - range: 1-100000

这样可以生成10万个公司名为公司1 公司2 公司3... 公司1000000的数据。

然后类推。

每种数据之间的关联只要保证好id的range列表对应上即可。

**Comment by dropping** [comment]
> 我理解的应该是有五种数据：
> 
> 1. 企业数据。
> 2. 人的数据。
> 3. 企业和企业的交易。
> 4. 人和企业的交易。
> 5. 人和人的交易。
>    用zd来生成的话，可以定义五种数据。还是很好定义的。
> 
> 企业：
> fields:
> 
> * field: id
> * range: 1-100000
> * field: name
> * prefix: 公司
> * range: 1-100000
> 
> 这样可以生成10万个公司名为公司1 公司2 公司3... 公司1000000的数据。
> 
> 然后类推。
> 
> 每种数据之间的关联只要保证好id的range列表对应上即可。

要实现单群体最大节点数 100， 这个需要图算法（比如随机网络模型 barabasi_albert_graph）的，A>B>C>D，只要有关联就在一个联调图（单群体）里面

**Comment by easysoft** [comment]
图算法没有研究过，你们可以试试看看能不能满足你们的要求。zd数据之间的关联性是靠设计者对各个字段的range列表进行精确控制来实现的。只要数据有规则，从理论上来讲，都可以配置出来。
