### ISSUE TITLE
不能成功编译

### ISSUE THREAD

**Issue by slackwarelinux** [easysoft/zendata#34]
### 错误信息
start compile linux
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC=/usr/local/gcc-4.8.1-for-linux64/bin/x86_64-pc-linux-gcc CXX=/usr/local/gcc-4.8.1-for-linux64/bin/x86_64-pc-linux-g++ go build -o bin/zd/2.1/linux/zd/zd src/zd.go
src/zd.go:6:2: no required module provides package github.com/easysoft/zendata/res; to add it:
        go get github.com/easysoft/zendata/res
make: *** [Makefile:45: compile_linux] Error 1

### zd.go
import (
	"flag"
	"fmt"
	"github.com/easysoft/zendata/res"
	"github.com/easysoft/zendata/src/action"
	"github.com/easysoft/zendata/src/gen"
	"github.com/easysoft/zendata/src/server"
	serverConfig "github.com/easysoft/zendata/src/server/config"
	serverUtils "github.com/easysoft/zendata/src/server/utils"
	serverConst "github.com/easysoft/zendata/src/server/utils/const"
	"github.com/easysoft/zendata/src/service"
	commonUtils "github.com/easysoft/zendata/src/utils/common"
	configUtils "github.com/easysoft/zendata/src/utils/config"
	constant "github.com/easysoft/zendata/src/utils/const"
	fileUtils "github.com/easysoft/zendata/src/utils/file"
	i118Utils "github.com/easysoft/zendata/src/utils/i118"
	logUtils "github.com/easysoft/zendata/src/utils/log"
	stringUtils "github.com/easysoft/zendata/src/utils/string"
	"github.com/easysoft/zendata/src/utils/vari"
	assetfs "github.com/elazarl/go-bindata-assetfs"
	"github.com/fatih/color"
	"io/ioutil"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"
)

### .gitignore
/log/
/.idea/
/build/
/tmp/cache/.data.db-shm
/tmp/cache/.data.db-wal
/demo/out/
/conf/
/bin/
/test/ztf/output/
/test/ztf/.idea/
/nohup.out
/test/ztf/conf/
/test/ztf/log/
/demo/out/
/test/ztf/._config.yaml
/test/ztf/._default.yaml
/._config.yaml
/._default.yaml
/res/res.go
/tmp/.temp.yaml
/tmp/.default.yaml
/tmp/.config.yaml
/qshell.log
/log-zd/
/data/test/
/test/out/
/yaml/article/chinese/slang/out/
/runtime/protobuf/go
/runtime/protobuf/out/
/users/common/

**Comment by slackwarelinux** [comment]
![2022-01-21_11-35](https://user-images.githubusercontent.com/2645109/150462649-a2b23659-0b2c-4a66-8503-8d7b36ebe5d5.png)
![2022-01-21_11-34_1](https://user-images.githubusercontent.com/2645109/150462659-4c2d4205-fba9-4902-a29b-381fbb146e08.png)
![2022-01-21_11-34](https://user-images.githubusercontent.com/2645109/150462663-d9ec30fb-04a6-4e7b-9d61-3c8587d689fd.png)

**Comment by aaronchen2k** [comment]
请先执行一下makefile里的go-bindata命令，生成res.go。
