### ISSUE TITLE
加载资源文件失败

### ISSUE THREAD

**Issue by slackwarelinux** [easysoft/zendata#35]
![Screenshot from 2022-01-21 12-20-54](https://user-images.githubusercontent.com/2645109/150465204-0a4bc161-64d3-40d6-acef-1bc4badbb6e1.png)

**Comment by aaronchen2k** [comment]
可去掉yaml的前缀，使用uuid.v1.yaml引用即可。
另已支持ULID：
`fields:
  - field: f1
    from: uuid.v2.yaml
    use: by_format
    postfix: "\t"

  - field: f2
    from: ulid.v1.yaml
    use: ulid{3}`
