### ISSUE TITLE
怎么在json里面嵌套json的数组

### ISSUE THREAD

**Issue by Clared1** [easysoft/zendata#38]
类似这样的数据格式要怎么生成呢，尝试使用你们官网的链接，但不起作用，做不到嵌套的效果
> https://www.zendata.cn/book/zendata/why-zendata-115.html
[](ttps://www.zendata.cn/book/zendata/why-zendata-115.html)
```
{
a:{
     c:2,
     d:3
},
b:1
}
```

**Comment by aaronchen2k** [comment]
目前输出的数据为一个二维表格，不支持输出嵌套的JSON数据。
