### ISSUE TITLE
outdated documents that cannot be called

### ISSUE THREAD

**Issue by maojunxyz** [easysoft/zendata#40]
version: 2.2

```sh
zd.exe -p 8848
```
```
客户端调用：

$curl http://localhost:8848/?d=demo/default.yaml&c=demo/config.yaml&n=100&T=true    # 通过GET方式指定服务器端配置文件。
$curl http://localhost:8848/?default=demo/default.yaml&output=test.sql&table=user   # 参数名可以用全拼。
$curl -i -X POST http://localhost:8848?lines=3 -F default=@demo/default.yaml        # 可以通过POST方式上传配置文件。
```

It doesn't work.

**Comment by aaronchen2k** [comment]
Will check it this afternoon, thank you for your feedback.

**Comment by aaronchen2k** [comment]
pls add “data” before "?d=" , e.x. 
`http://localhost:8848/data?d=demo/default.yaml&c=demo/config.yaml&n=100&T=true`

<img width="966" alt="image" src="https://user-images.githubusercontent.com/3222874/196645435-77b84727-a746-4c46-8e7f-96a53208941f.png">

**Comment by maojunxyz** [comment]
tks,it works. But there are still several problems, the format specified by output does not work。

- eg no.1 :
```
$curl http://localhost:8848/?default=demo/default.yaml&output=test.sql&table=user   # 参数名可以用全拼。
```
I think this command should return sql text data, not json data.
- eg no.2:
```
$curl -i -X POST http://localhost:8848?lines=3 -F default=@demo/default.yaml        # 可以通过POST方式上传配置文件。
```
I don't quite understand this command, is it uploading the local configuration to the server? But it doesn't seem to work

**Comment by aaronchen2k** [comment]
1. Serive only support JSON format output.
2. Curl post the file contents to server, post sample miss the /data path too, which is fixed.
