### ISSUE TITLE
定义数据文件类型

### ISSUE THREAD

**Issue by yangyangpig** [easysoft/zendata#7]
目前只能支持yaml格式文件吗？能否支持proto文件，基于proto定义的rpc服务生成对应的response数据？

**Comment by aaronchen2k** [comment]
目前只支持yaml数据格式和http协议请求。

**Comment by easysoft** [comment]
二进制格式数据的生成也是我们下一步发展的方向。敬请关注。

**Comment by aaronchen2k** [comment]
@yangyangpig 我QQ 462826加你好友了，方便的话我们聊一下proto有关的需求。
